#!/bin/bash
IsInstalled() {
    version="$1"
    . "$script_pwd/../partitioners/$version"
    IsInstalled
    return
}

Binary() {
    version="$1"
    . "$script_pwd/../partitioners/$version"
    Binary
}

Install() {
    . "$script_pwd/../partitioners/$version"
    Install "" $2
    return
}

InvokeFromDisk() {
    . "$scirpt_pwd/../partitioners/$version"
    InvokeFromDisk "" ${@:2}
    return
}

InvokeFromKaGen() {
    . "$scirpt_pwd/../partitioners/$version"
    InvokeFromKaGen "" ${@:2}
    return
}
