#!/bin/bash

Fetch() {
    return
}

FetchDiskDriver() {
    return
}

Install() {
    local -n install_args=$1

    # Jet must be build manually and be placed in:
    # $HOME/usr<host id>/bin/jet
    if (( ${install_args[install_disk_driver]} )); then 
        HOST=$(hostname) # i10pc<host id>
        HOST=${HOST:5} # <host id>
        import_filename="$HOME/usr$HOST/bin/jet"

        if [[ ! -f "$import_filename" ]]; then
            echo "Error: Jet binary not found at $import_filename"
            exit 1
        fi

        Prefixed cp "$import_filename" "${install_args[disk_driver_bin]}"
    fi

    if (( ${install_args[install_kagen_driver]} )); then 
        echo "Error: KaGen support not implemented for MtKaHyPar"
        exit 1
    fi
}

InvokeFromDisk() {
    local -n invoke_from_disk_args=$1

    graph="${invoke_from_disk_args[graph]}"
    if [[ -f "$graph.graph" ]]; then
        graph="$graph.graph"
    elif [[ -f "$graph.metis" ]]; then
        graph="$graph.metis"
    fi

    config="$job_files_dir/jet-configs/k${invoke_from_disk_args[k]}.txt"
    if [[ ! -d "$job_files_dir/jet-configs/" ]]; then
        mkdir -p "$job_files_dir/jet-configs/"
    fi
    if [[ ! -f "$config" ]]; then
        echo "0" >> "$config"
        echo "${invoke_from_disk_args[k]}" >> "$config"
        echo "1" >> "$config"
        echo "1.03" >> "$config"
    fi

    if [[ -f "$graph" ]]; then
        echo -n "${invoke_from_disk_args[bin]} "
        echo -n "$graph "
        echo -n "$config"
        echo ""
    else 
        >&2 echo "Warning: Graph $graph does not exist"
        return 1
    fi
}

ReportVersion() {
    return
}
