#!/bin/bash

. "$script_pwd/../partitioners/inc/git.sh"
. "$script_pwd/../partitioners/inc/kagen-partitioner.sh"

Fetch() {
    local -n fetch_args=$1

    if (( ${fetch_args[install_disk_driver]} )); then 
        FetchDiskDriver fetch_args
    fi
    if (( ${fetch_args[install_kagen_driver]} )); then 
        GenericKaGenPartitionerFetch fetch_args
    fi
}

FetchDiskDriver() {
    GenericGitFetch $1 "https://github.com/KaHIP/KaHIP.git" "disk_driver_src"
}

Install() {
    local -n install_args=$1
    
    if (( ${install_args[install_disk_driver]} )); then 
        InstallDiskDriver install_args
    fi
    if (( ${install_args[install_kagen_driver]} )); then 
        GenericKaGenPartitionerInstall install_args "-DBUILD_MTKAHIP=Off -DBUILD_KAHIP=On" "KaHIP"
    fi
}

InstallDiskDriver() {
    local -n install_disk_driver_args=$1

    src_dir="${install_disk_driver_args[disk_driver_src]}"

    echo -e "Build algorithm '$ALGO_COLOR${install_disk_driver_args[algorithm]}$NO_COLOR' in directory '$src_dir'"
    echo -e "  - System-specific CMake options: ${WARNING_COLOR}ignored$NO_COLOR"
    echo -e "  - Algorithm-specific options (passed to compile_withcmake.sh): $ARGS_COLOR${install_disk_driver_args[algorithm_build_options]}$NO_COLOR"
    echo ""

    current_pwd="$PWD"

    cd "$src_dir"
    #export CMAKE_GENERATOR="Unix Makefiles"
    CMAKE_GENERATOR="Unix Makefiles" Prefixed ./compile_withcmake.sh ${install_disk_driver_args[algorithm_build_options]}
    cd "$current_pwd"
    Prefixed cp "$src_dir/deploy/kaffpa" "${install_disk_driver_args[disk_driver_bin]}"
}

InvokeFromDisk() {
    local -n invoke_from_disk_args=$1
    
    graph="${invoke_from_disk_args[graph]}"
    [[ -f "$graph.graph" ]] && graph="$graph.graph"
    [[ -f "$graph.metis" ]] && graph="$graph.metis"
    imbalance=$(echo "100*${invoke_from_disk_args[epsilon]}/1" | bc)

    if [[ "${invoke_from_disk_args[print_partitioner]}" == "1" ]]; then 
        >&2 echo -e "Generating calls for algorithm '$ALGO_COLOR${invoke_from_disk_args[algorithm]}$NO_COLOR', from disk, via the binary:"
        >&2 echo "  - Binary: ${invoke_from_disk_args[bin]}"
        >&2 echo "  - Generated arguments: "
        >&2 echo -e "      --k=$ARGS_COLOR${invoke_from_disk_args[k]}$NO_COLOR"
        >&2 echo -e "      --imbalance=$ARGS_COLOR$imbalance$NO_COLOR"
        >&2 echo -e "      --seed=$ARGS_COLOR${invoke_from_disk_args[seed]}$NO_COLOR"
        >&2 echo -e "      $ARGS_COLOR$graph$NO_COLOR"
        >&2 echo -e "  - Specified arguments: $ARGS_COLOR${invoke_from_disk_args[algorithm_arguments]}$NO_COLOR"
        >&2 echo ""
    fi

    if [[ -f "$graph" ]]; then
        echo -n "${invoke_from_disk_args[bin]} "
        echo -n "--k=${invoke_from_disk_args[k]} "
        echo -n "--imbalance=$imbalance "
        echo -n "--seed=${invoke_from_disk_args[seed]} "
        echo -n "$graph "
        echo -n "${invoke_from_disk_args[algorithm_arguments]}"
        echo ""
    else 
        >&2 echo "Warning: Graph $graph does not exist"
        return 1
    fi
}

InvokeFromKaGen() {
    GenericKaGenPartitionerInvokeFromKaGen $1
}

ReportVersion() {
    GenericGitReportVersion $1
}
