#!/bin/bash

. "$script_pwd/../partitioners/inc/git.sh"
. "$script_pwd/../partitioners/inc/kagen-partitioner.sh"

KAMINPAR_USE_PUBLIC_REPOSITORY=0

. "$script_pwd/../partitioners/inc/kaminpar.sh"

InstallDiskDriver() {
    local -n install_disk_driver_args=$1
    src_dir="${install_disk_driver_args[disk_driver_src]}"

    Prefixed cmake -S "$src_dir" \
        -B "$src_dir/build" \
        -DCMAKE_BUILD_TYPE=Release \
        -DKAMINPAR_BUILD_DISTRIBUTED=Off \
        -DKAMINPAR_BUILD_BENCHMARKS=On \
        $CUSTOM_CMAKE_FLAGS \
        ${install_disk_driver_args[algorithm_build_options]}
    Prefixed cmake --build "$src_dir/build" --target shm_refinement_benchmark --parallel
    Prefixed cp "$src_dir/build/apps/benchmarks/shm_refinement_benchmark" "${install_disk_driver_args[disk_driver_bin]}"
}

InvokeFromDisk() {
    local -n invoke_from_disk_args=$1
    
    graph="${invoke_from_disk_args[graph]}"
    [[ -f "$graph.graph" ]] && graph="$graph.graph"
    [[ -f "$graph.metis" ]] && graph="$graph.metis"

    if [[ -f "$graph" ]]; then
        echo -n "${invoke_from_disk_args[bin]} "
        echo -n "-t ${invoke_from_disk_args[num_threads]} "
        echo -n "$graph "
        echo -n "${invoke_from_disk_args[algorithm_arguments]}"
        echo ""
        #echo -n "-k ${invoke_from_disk_args[k]} "
        #echo -n "-e ${invoke_from_disk_args[epsilon]} "
        #echo -n "--seed=${invoke_from_disk_args[seed]} "
        #echo -n "-T "
    else 
        >&2 echo "Warning: Graph $graph does not exist; skipping instance"
        return 1
    fi
}

