#!/bin/bash

Fetch() {
    local -n fetch_args=$1

    if (( ${fetch_args[install_disk_driver]} )); then 
        FetchDiskDriver fetch_args
    fi
}

FetchDiskDriver() {
    local -n fetch_disk_driver_args=$1
    src_dir="${fetch_disk_driver_args[disk_driver_src]}"

    if [[ ! -d "$src_dir/kaminpar_copy/" ]]; then
        echo -e "Downloading self-hosted tar for algorithm '$ALGO_COLOR${fetch_disk_driver_args[algorithm]}$NO_COLOR' to directory '$src_dir'"
        echo ""

        Prefixed mkdir -p "$src_dir"
        Prefixed curl -o "$src_dir/KaMinPar_release.tar.gz" "https://ae.iti.kit.edu/documents/research/deep_mgp/KaMinPar_release.tar.gz"
        Prefixed tar -xzf "$src_dir/KaMinPar_release.tar.gz" -C "$src_dir"

        # CMakeLists requires the project to be in a Git repository ...
        Prefixed git -C "$src_dir/kaminpar_copy" init -b master
        Prefixed git -C "$src_dir/kaminpar_copy" add "README.MD"
        Prefixed git -C "$src_dir/kaminpar_copy" commit -m "dummy commit"
    else
        echo "Directory '$src_dir/kaminpar_copy/' already exists, skipping download"
        echo -e "${WARNING_COLOR}If you intend to re-download KaMinPar, delete the directory!$NO_COLOR"
        echo ""
    fi
}

Install() {
    local -n install_args=$1
    
    if (( ${install_args[install_disk_driver]} )); then 
        InstallDiskDriver install_args
    fi
}

InstallDiskDriver() {
    local -n install_disk_driver_args=$1

    if [[ ! -x "${install_disk_driver_args[disk_driver_bin]}" ]]; then
        src_dir="${install_disk_driver_args[disk_driver_src]}"

        echo -e "Build algorithm '$ALGO_COLOR${install_disk_driver_args[algorithm]}$NO_COLOR' in directory '$src_dir'"
        echo -e "  - System-specific CMake options: $CUSTOM_CMAKE_FLAGS"
        echo -e "  - Algorithm-specific options (passed to compile_withcmake.sh): $ARGS_COLOR${install_disk_driver_args[algorithm_build_options]}$NO_COLOR"
        echo ""

        current_pwd="$PWD"
        cd "$src_dir/kaminpar_copy/"
        Prefixed cmake -B "build" -DCMAKE_BUILD_TYPE=Release
        Prefixed cmake --build "build" --target KaMinPar --parallel

        Prefixed cp "$src_dir/kaminpar_copy/build/apps/KaMinPar" "${install_disk_driver_args[disk_driver_bin]}"
        cd "$current_pwd"
    else
        echo "Binary '${install_disk_driver_args[disk_driver_bin]}' already exists, skipping build"
        echo -e "${WARNING_COLOR}If you intend to rebuild KaMinPar, delete the binary!$NO_COLOR"
        echo ""
    fi
}

InvokeFromDisk() {
    local -n invoke_from_disk_args=$1
    
    graph="${invoke_from_disk_args[graph]}"
    [[ -f "$graph.graph" ]] && graph="$graph.graph"
    [[ -f "$graph.metis" ]] && graph="$graph.metis"

    if [[ "${invoke_from_disk_args[print_partitioner]}" == "1" ]]; then 
        >&2 echo -e "Generating calls for algorithm '$ALGO_COLOR${invoke_from_disk_args[algorithm]}$NO_COLOR', from disk, via the binary:"
        >&2 echo "  - Binary: ${invoke_from_disk_args[bin]}"
        >&2 echo "  - Generated arguments: "
        >&2 echo -e "      -G $ARGS_COLOR$graph$NO_COLOR"
        >&2 echo -e "      -k $ARGS_COLOR${invoke_from_disk_args[k]}$NO_COLOR"
        >&2 echo -e "      --seed=$ARGS_COLOR${invoke_from_disk_args[seed]}$NO_COLOR"
        >&2 echo -e "      -e $ARGS_COLOR${invoke_from_disk_args[epsilon]}$NO_COLOR"
        >&2 echo -e "      -t $ARGS_COLOR${invoke_from_disk_args[num_threads]}$NO_COLOR"
        >&2 echo -e "  - Specified arguments: $ARGS_COLOR${invoke_from_disk_args[algorithm_arguments]}$NO_COLOR"
        >&2 echo "[...]"
        >&2 echo ""
    fi

    if [[ -f "$graph" ]]; then
        echo -n "${invoke_from_disk_args[bin]} "
        echo -n "-G $graph "
        echo -n "-k ${invoke_from_disk_args[k]} "
        echo -n "--seed=${invoke_from_disk_args[seed]} "
        echo -n "-e ${invoke_from_disk_args[epsilon]} "
        echo -n "-t ${invoke_from_disk_args[num_threads]} "
        echo -n "${invoke_from_disk_args[algorithm_arguments]}"
        echo ""
    else 
        >&2 echo "Warning: Graph $graph does not exist"
        return 1
    fi
}

ReportVersion() {
    echo "*:ESA21release"
}
