#!/bin/bash

. "$script_pwd/../partitioners/inc/git.sh"
. "$script_pwd/../partitioners/inc/kagen-partitioner.sh"

KAMINPAR_REPOSITORY_URL="git@github.com:KaHIP/KaMinPar.git"

. "$script_pwd/../partitioners/inc/kaminpar.sh"
