#!/bin/bash
. "$script_pwd/../partitioners/_KaGenPartitioner"

Install() {
    src_dir="$PREFIX/src/KaGen-Partitioner/"

    if [[ ! -d "$src_dir" ]]; then 
        git clone git@github.com:KaHIP/KaGen-Partitioner.git "$src_dir"
    else 
        git -C "$src_dir" pull
    fi
    
    cmake -S "$src_dir" -B "$src_dir/build" -DCMAKE_BUILD_TYPE=Release -DBUILD_MTKAHIP=Off -DBUILD_MTKAHYPAR=On
    cmake --build "$src_dir/build" --parallel
    cp "$src_dir/build/MtKaHyPar" "${args[binary_disk]}"
    cp "$src_dir/build/MtKaHyPar" "${args[binary_kagen]}"
}
