#!/bin/bash
IsInstalled() {
    if [[ ! -x "$GLOBAL_PREFIX/bin/pm_parmetis" ]]; then
        return 1
    fi
    if [[ ! -x "$GLOBAL_PREFIX/bin/InMemoryParmetis" ]]; then 
        return 1 
    fi

    return 0
}

Binary() {
    echo "$GLOBAL_PREFIX/bin/pm_parmetis"
}

Install() {
    if [[ "$version" != "latest" ]]; then
        echo "Error: version support not implemented"
        exit 1
    fi 

    if IsInstalled; then 
        return 0
    fi

    current_pwd="$PWD"

    export CMAKE_GENERATOR="Unix Makefiles" 

    # Install GKlib
    if [[ ! -f "$GLOBAL_PREFIX/lib/libGKlib.a" ]]; then 
        src_gklib="$GLOBAL_PREFIX/src/GKlib"
        if [[ ! -d "$src_gklib" ]]; then 
            git clone git@github.com:KarypisLab/GKlib.git "$src_gklib"
        else
            git -C "$src_gklib" pull 
        fi

        cd "$src_gklib" 
        make config prefix="$GLOBAL_PREFIX"
        make
        make install
        cd "$current_pwd"
    fi

    # Install METIS 
    if [[ ! -f "$GLOBAL_PREFIX/lib/libmetis.a" ]]; then 
        src_metis="$GLOBAL_PREFIX/src/METIS"
        if [[ ! -d "$src_metis" ]]; then 
            git clone https://github.com/KarypisLab/METIS.git "$src_metis"
        else 
            git -C "$src_metis" pull 
        fi

        cd "$src_metis"
        make config prefix="$GLOBAL_PREFIX" i64=1
        make install
        cd "$current_pwd"
    fi

    # Standalone ParMETIS
    if [[ ! -f "$GLOBAL_PREFIX/bin/pm_parmetis" ]]; then 
        src_parmetis="$GLOBAL_PREFIX/src/ParMETIS"
        if [[ ! -d "$src_parmetis" ]]; then
            git clone git@github.com:KarypisLab/ParMETIS.git "$src_parmetis"
        fi

        # Current master does not compile
        git -C "$src_parmetis" checkout bd219d2982c29d91c84b1a486e53206d29e8ec7a

        # Patch main to allow custom epsilons
        cp "$ROOT/src/parmetis.c" "$src_parmetis/programs/parmetis.c"

        cd "$src_parmetis"
        make config prefix="$GLOBAL_PREFIX"
        make install
        cd "$current_pwd"
    fi

    if [[ ! -x "$GLOBAL_PREFIX/bin/ParMETIS_KaGen" ]]; then # Requirement: KaGen
        src_dir="$GLOBAL_PREFIX/src/KaGen-Partitioner"
        if [[ ! -d "$src_dir" ]]; then
            git clone git@github.com:KaHIP/KaGen-Partitioner.git "$src_dir"
        else 
            git -C "$src_dir" pull 
        fi
        
        cmake -S "$src_dir" -B "$src_dir/build" -DCMAKE_BUILD_TYPE=Release -DDKAMINPAR=On -DXTRAPULP=On "$TBB_FLAG" $2
        cmake --build "$src_dir/build" --parallel
    
        cp "$src_dir/build/ParHIP" "$GLOBAL_PREFIX/bin/ParHIP_KaGen"
        cp "$src_dir/build/ParMETIS" "$GLOBAL_PREFIX/bin/ParMETIS_KaGen"
        cp "$src_dir/build/dKaMinPar" "$GLOBAL_PREFIX/bin/dKaMinPar_KaGen"
        cp "$src_dir/build/XtraPuLP" "$GLOBAL_PREFIX/bin/XtraPuLP_KaGen"
    fi 
}

InvokeFromDisk() {
    version="$1"
    graph="$2"
    k="$3"
    epsilon="$4"
    seed="$5"
    threads="$6"
    arguments="${@:9}"
  
    # .graph > .metis
    [[ -f "$graph.graph" ]] && graph="$graph.graph"
    [[ -f "$graph.metis" ]] && graph="$graph.metis"

    if [[ -f "$graph" ]]; then
        echo "$(Binary) $graph 1 $k 0 0 3 $seed $epsilon"
    else 
        >&2 echo "Warning: Graph $graph does not exist"
        return 1
    fi
}

InvokeFromKaGen() {
    param_version="$1"
    param_generator="$2"
    param_k="$3"
    param_epsilon="$4"
    param_seed="$5"
    param_nodes="$6"
    param_threads="$8"
    param_kagen_arguments="$9"
    param_algo_arguments="${@:10}"

    echo -n "$GLOBAL_PREFIX/bin/ParMETIS_KaGen "
    echo -n "-s $param_seed " # interprete as number of repetitions 
    echo -n "-k $param_k "

    echo -n "-G\"$param_generator"

    kagen_n=$(ParseKaGenArgument "n" $param_kagen_arguments)
    kagen_m=$(ParseKaGenArgument "m" $param_kagen_arguments)
    kagen_p=$(ParseKaGenArgument "p" $param_kagen_arguments)
    kagen_a=$(ParseKaGenArgument "a" $param_kagen_arguments)
    kagen_b=$(ParseKaGenArgument "b" $param_kagen_arguments)
    kagen_c=$(ParseKaGenArgument "c" $param_kagen_arguments)
    kagen_gamma=$(ParseKaGenArgument "gamma" $param_kagen_arguments)

    log_nodes=$(printf "%.0f" $(echo "l($param_nodes)/l(2)" | bc -l))

    if [[ ! -z "$kagen_a" ]]; then 
        echo -n ";rmat_a=$kagen_a;rmat_b=$kagen_b;rmat_c=$kagen_c"
    fi
    if [[ ! -z "$kagen_p" ]]; then 
        echo -n ";prob=$kagen_p"
    fi
    if [[ ! -z "$kagen_gamma" ]]; then 
        echo -n ";gamma=$kagen_gamma"
    fi
    if [[ ! -z "$kagen_n" ]]; then 
        echo -n ";N=$((kagen_n+log_nodes))" # log n
    fi
    if [[ ! -z "$kagen_m" ]]; then 
        echo -n ";M=$((kagen_m+log_nodes))" # log m
    fi

    echo -n "\""
    echo ""
}
