#!/bin/bash

. "$script_pwd/../partitioners/inc/kagen-partitioner.sh"

Fetch() {
    local -n args=$1
    GenericKaGenPartitionerFetch args
}

Install() {
    local -n args=$1
    GenericKaGenPartitionerInstall args -DBUILD_XTRAPULP=On "XtraPuLP"
}

InvokeFromDisk() {
    local -n args
    GenericKaGenPartitionerInvokeFromDisk args
}

InvokeFromKaGen() {
    local -n args
    GenericKaGenPartitionerInvokeFromKaGen args
}

