#!/bin/bash 
system_cores_per_node="$(getconf _NPROCESSORS_ONLN 2>/dev/null)"
system_max_cores_per_node="$system_cores_per_node"

system_validate() {
    return 0
}

system_generate_slurm_job_header() {
    return 0
}

system_generate_mpi_cmd() {
    echo "mpirun -n $((system_cores_per_node*nodes/param_cores)) --bind-to core --map-by socket:PE=${param_cores} "
}
