#!/bin/bash 

gbl_cores_per_node=64
gbl_max_cores_per_node=78

gbl_generate_slurm_job_header() {
    echo "#SBATCH --nodes=${param_nodes}"
    echo "#SBATCH --ntasks=$((param_nodes*param_cores))"
    echo "#SBATCH --cpus-per-task=${param_cores}"
    echo "#SBATCH --ntasks-per-node=$((gbl_cores_per_node/param_cores))"
    echo "#SBATCH --time=${param_time}"
    echo "#SBATCH --export=ALL"
    echo "#SBATCH --mem=230gb"
    echo "#SBATCH --partition=cpuonly"
    echo "module load mpi/openmpi/4.0"
}

gbl_generate_mpi_cmd() {
    echo "mpirun -n $((gbl_cores_per_node*param_nodes/param_cores)) --bind-to core --map-by socket:PE=${param_cores} "
}
