#!/bin/bash
DefineAlgorithmBuild KaMinPar64 KaMinPar --preset=default -DKAMINPAR_64BIT_IDS=On
#DefineAlgorithmBuild KaMinParC KaMinPar --preset=compressed

DefineAlgorithm KaMinPar-FM KaMinPar -P fm
#DefineAlgorithm KaMinPar-Mem KaMinParC -P memory

System i10
Wrapper taskset

ExperimentUfmBench() {
    Algorithms KaMinPar 

    Ks 2 4 8 16 32 64 128
    Seeds 1 2 3
    Threads 1x1x4 1x1x64

    # Graphs /nfs/work/graph_benchmark_sets/ufm_paper/combined metis
    Graphs /nfs/work/graph_benchmark_sets/ufm_paper/combined_32eid_nzcut metis
}
