#!/bin/bash

. "$script_pwd/../partitioners/inc/kagen-partitioner.sh"

Fetch() {
    GenericKaGenPartitionerFetch $1
}

Install() {
    GenericKaGenPartitionerInstall $1 "-DBUILD_MTKAHYPAR=Off -DBUILD_MTKAHIP=On" "MtKaHIP"
}

InvokeFromDisk() {
    GenericKaGenPartitionerInvokeFromDisk $1
}

InvokeFromKaGen() {
    GenericKaGenPartitionerInvokeFromKaGen $1
}

