#!/bin/bash 
GenerateJobfileHeader() {
    return 0
}

GenerateJobfileEntry() {
    mpi="$1"
    nodes="$2"
    mpis="$3"
    threads="$4"
    exe="$5"

    if (( $nodes > 1 )); then
        >&2 echo "Error: generic systems do not support multi-node execution"
        exit 1
    fi

    case "$mpi" in 
        none)
            echo "$exe"
            ;;
        OpenMPI)
            echo "mpirun -n $mpis --bind-to core --map-by socket:PE=${threads} $exe"
            ;;
        *)
            >&2 echo "Error: unsupported MPI $mpi"
            exit 1
    esac
}

GenerateJobfileSubmission() {
    for jobfile in ${@}; do
        echo "bash $jobfile"
    done
}
