#!/bin/bash 
system_cores_per_node=64
system_max_cores_per_node=78

system_validate() {
    if [[ "$param_mpi" != "openmpi" ]]; then
        echo "Error: unsupported mpi implementation"
        return 1
    fi

    return 0
}

system_generate_slurm_job_header() {
    echo "#SBATCH --nodes=${param_nodes}"
    echo "#SBATCH --ntasks=$((param_nodes*param_cores))"
    echo "#SBATCH --cpus-per-task=${param_cores}"
    echo "#SBATCH --ntasks-per-node=$((system_cores_per_node/param_cores))"
    echo "#SBATCH --time=${param_time}"
    echo "#SBATCH --export=ALL"
    echo "#SBATCH --mem=230gb"
    echo "#SBATCH --partition=cpuonly"
    echo "module load mpi/openmpi/4.0"
}

system_generate_mpi_cmd() {
    echo "mpirun -n $((system_cores_per_node*param_nodes/param_cores)) --bind-to core --map-by socket:PE=${param_cores} "
}
