#!/bin/bash 

# HoreKa with OpenMP: sets OMP_NUM_THREADS

. "$script_pwd/../systems/HoreKa"

GenerateJobfileHeader() {
    local -n args=$1

    >&2 echo -e "Generating jobfile header for parallel execution mode $ARGS_COLOR${args[num_nodes]}x${args[num_mpis]}x${args[num_threads]}$NO_COLOR:"
    >&2 echo -e "  --nodes=$ARGS_COLOR${args[num_nodes]}$NO_COLOR"
    >&2 echo -e "  --ntasks=$ARGS_COLOR$((args[num_nodes]*args[num_mpis]))$NO_COLOR"
    >&2 echo -e "  --cpus-per-task=$ARGS_COLOR${args[num_threads]}$NO_COLOR"
    >&2 echo -e "  --ntasks-per-node=$ARGS_COLOR${args[num_mpis]}$NO_COLOR"
    >&2 echo -e "  --time=$ARGS_COLOR${args[timelimit]}$NO_COLOR"
    >&2 echo "  --export=ALL"
    >&2 echo "  --mem=230gb"
    >&2 echo "  --partition=cpuonly"

    echo "#!/bin/bash"
    echo "#SBATCH --nodes=${args[num_nodes]}"
    echo "#SBATCH --ntasks=$((args[num_nodes]*args[num_mpis]))"
    echo "#SBATCH --cpus-per-task=${args[num_threads]}"
    echo "#SBATCH --ntasks-per-node=${args[num_mpis]}"
    echo "#SBATCH --time=${args[timelimit]}"
    echo "#SBATCH --export=ALL"
    echo "#SBATCH --mem=230gb"
    echo "#SBATCH --partition=cpuonly"

    if [[ "${args[mpi]}" == "OpenMPI" ]]; then 
        >&2 echo "Running jobs with OpenMPI version ${HOREKA_OPENMPI_VERSION}"
        echo "module load mpi/openmpi/${HOREKA_OPENMPI_VERSION}"
    fi

    >&2 echo -e "Setting OMP_NUM_THREADS=$ARGS_COLOR${args[num_threads]}$NO_COLOR"
    echo "export OMP_NUM_THREADS=${args[num_threads]}"

    >&2 echo ""
}

