#!/bin/bash 
HOREKA_OPENMPI_VERSION="4.0"
TBB_FLAG="-DTBB_DIR=/hkfs/home/software/all/toolkit/Intel_OneAPI/tbb/2021.2.0/lib/cmake/tbb"

GenerateJobfileHeader() {
    param_mpi="$1"
    param_nodes="$2"
    param_mpis="$3"
    param_threads="$4"
    param_timelimit="$5"

    echo "#!/bin/bash"
    echo "#SBATCH --nodes=${param_nodes}"
    echo "#SBATCH --ntasks=$((param_nodes*param_mpis))"
    echo "#SBATCH --cpus-per-task=${param_threads}"
    echo "#SBATCH --ntasks-per-node=${param_mpis}"
    echo "#SBATCH --time=${param_timelimit}"
    echo "#SBATCH --export=ALL"
    echo "#SBATCH --mem=230gb"
    echo "#SBATCH --partition=cpuonly"

    if [[ "$param_mpi" == "OpenMPI" ]]; then 
        echo "module load mpi/openmpi/${HOREKA_OPENMPI_VERSION}"
    fi
}

GenerateJobfileEntry() {
    param_nodes="$1"
    param_mpis="$2"
    param_threads="$3"
    param_exe="$4"

    case "$_mpi" in
        none)
            >&2 echo "Error: application must be run with MPI"
            exit 1
            ;;
        OpenMPI)
            #echo "mpirun -n $((param_nodes*param_mpis)) --bind-to core --map-by socket:PE=${param_threads} -report-bindings ${param_exe}"
            echo "mpirun -n $((param_nodes*param_mpis)) --bind-to core --map-by socket:PE=${param_threads} ${param_exe}"
            ;;
        *)
            >&2 echo "Error: unsupported MPI $_mpi"
            exit 1
    esac
}

GenerateJobfileSubmission() {
    for jobfile in ${@}; do 
        echo "sbatch $jobfile"
    done
}

