#!/bin/bash 
. "$script_pwd/../systems/Generic"

# i10*: runs the experiment through `exclusive`

GenerateJobfileSubmission() {
    for file in ${@}; do 
        echo "bash $file" >> "$submit_impl_filename"
    done
}

GenerateJobfileWrapper() {
    >&2 echo -e "Running experiment using ${ARGS_COLOR}nonexclusive$NO_COLOR"
    >&2 echo ""

    echo "nohup nonexclusive bash -- $submit_impl_filename &"
    echo "disown"
}
