#!/bin/bash 
. "$script_pwd/../systems/Generic"

# i10*: run the experiment through `exclusive` *IN PARALLEL*,
# i.e., use one core per instance. 
# Only useful for sequential codes and experiments that do not need 
# accurate measurements of running times.

GenerateJobfileSubmission() {
    for file in ${@}; do 
        echo "parallel < $file" >> "$submit_impl_filename"
    done
}

GenerateJobfileWrapper() {
    >&2 echo -e "Running experiment using ${ARGS_COLOR}exclusive + parallel$NO_COLOR"
    >&2 echo ""

    echo "nohup exclusive bash -- $submit_impl_filename &"
    echo "disown"
}
