#!/bin/bash 
. "$script_pwd/../systems/generic"

# i10*: runs the experiment *without* `exclusive`
# (e.g., for running on the login node or when already holding an exclusive token)

GenerateJobfileSubmission() {
    for file in ${@}; do 
        echo "bash $file" >> "$submit_impl_filename"
    done
}

GenerateJobfileWrapper() {
    echo "nohup bash -- $submit_impl_filename &"
    echo "disown"
}
