#!/bin/bash 

# i10*: run the experiment through `exclusive` *IN PARALLEL*,
# i.e., use one core per instance. 
# Only useful for sequential codes and experiments that do not need 
# accurate measurements of running times.

. "$script_pwd/../systems/generic"

GenerateJobfileSubmission() {
    all_jobs_file="$PWD/all_jobs.sh"
    rm -rf "$all_jobs_file"
    touch "$all_jobs_file"
    chmod +x "$all_jobs_file"
    for file in ${@}; do 
        echo "parallel < $file" >> "$PWD/all_jobs.sh"
    done
    echo "nohup exclusive bash -- $all_jobs_file &"
    echo "disown"
}
