#!/bin/bash 

generate_slurm_job_header() {
    nodes="$1"
    cores="$2"
    time="$3"

    echo "#SBATCH --mail-type=NONE"
    echo "#SBATCH --time=${time}"
    echo "#SBATCH --no-requeue"
    echo "#SBATCH --export=NONE"
    echo "#SBATCH --get-user-env"
    echo "#SBATCH --account=${PRIV_SUPERMUC_PROJECT}"
    if (( $num_nodes <= 16 )); then 
        echo "#SBATCH --partition=micro"
    else 
        echo "#SBATCH --partition=general"
    fi
    echo "#SBATCH --nodes=${nodes}"
    echo "#SBATCH --ntasks=$((cores*nodes))"
    echo "#SBATCH --ntaks-per-node=$((32/cores))"
    echo "#SBATCH --mem=80gb"
    echo "#SBATCH --ear=off"
    echo "module load openmpi/4.0.7-gcc11"
    echo "module load slurm_setup"
}
